version: '3'

services:
  mysql_database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: aakash
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  nginxdb:
    image: nginx:latest
    restart: always
    depends_on:
      - mysql_database
    ports:
      - 8082:80
    volumes:
      - nginx_storage:/var/www/html

volumes:
  nginx_storage:
