version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 8085:80

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
